// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_bots': 'enable',
    'aws_bots_config': [{"name":"CovidSymptoms","alias":"$LATEST","description":"","bot-template":"bot-import","commands-help":[],"region":"us-west-2"}],
    'aws_cognito_identity_pool_id': 'us-west-2:d3771c62-310b-49b6-8500-aacdc2cca3a2',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'cloudcomputingprojec-hosting-mobilehub-180291652',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'db9130asxpbun.cloudfront.net',
    'aws_mobile_analytics_app_id': '2bae3e0d3bea4d5b9d32b501907ecce9',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'a6923838-78df-4961-8ff5-83600869c83b',
    'aws_project_name': 'Cloud-Computing-Project-2020-04-28-22-57-35',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'cloudcomputingprojec-mobilehub-180291652',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_8av6o8gd7',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '1fgto4rkg3t2i4dnphmfm8it8s',
}

export default awsmobile;
